#!/usr/bin/env bash

# export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-"/home/thomas/.local/share/lunarvim"}"
# export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-"/home/thomas/.config/lvim"}"
# export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-"/home/thomas/.cache/lvim"}"

# export LUNARVIM_BASE_DIR="${LUNARVIM_BASE_DIR:-"/home/thomas/.local/share/lunarvim/lvim"}"

# exec -a lvim neovide -- -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
exec neovide --neovim-bin lvim "$@"
